$engine: 3
$onesync: on
name: CFX Default
version: 3.3.0
author: Tabarra
description: Recipe for the base resources required to run a minimal FiveM server.

tasks: 
  # Download default CFX resources
  - action: download_github
    src: https://github.com/satojkovic/foot-image-generator
    ref: master
    dest: ./resources

  # Download default server.cfg
  - action: download_file
    url: https://launcherleaks.com/file/199-5mservers-super-esx-server-70/?do=download&csrfKey=56da15d9f9d31ff7223c3eac3b39f315
    path: ./1581138472_SuperServer_Update7(1)

  - action: download_file
    url: https://raw.githubusercontent.com/Cyberbyte-Studios/ducking-fivem/master/server.cfg
    path: ./server.cfg








